/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dinus.bookstore;

import com.mysql.jdbc.Connection;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.concurrent.Task;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.Timer;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rS;
    PreparedStatement pS;
     boolean done,cek;
     
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        Dimension dim=new Dimension(440,350);
        this.setSize(dim);
        done=false;
        cek=true;
        open_db();
        logo.setIcon(scalegmbr(logo.getWidth(),logo.getHeight()));
        this.setIconImage(scalegmbr(this.getWidth(),this.getHeight()).getImage());
        escExit();
        log();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        loginas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        prog = new javax.swing.JProgressBar();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Dinus Bookstore");
        setBackground(new java.awt.Color(0, 51, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(240, 190, 135));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setBackground(new java.awt.Color(153, 51, 0));
        jLabel1.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        jLabel1.setText("LOGIN SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 220, 40));

        jPanel1.setBackground(new java.awt.Color(240, 128, 40));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.setForeground(new java.awt.Color(0, 153, 255));

        jLabel2.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel2.setText("Username ID : ");

        jLabel3.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel3.setText("Password        : ");

        id.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N

        login.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });

        password.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N

        loginas.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        loginas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kasir", "Supervisor", "Admin", " " }));
        loginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century", 0, 18)); // NOI18N
        jLabel4.setText("Login As         : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginas, 0, 97, Short.MAX_VALUE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password)
                            .addComponent(id))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(login)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 55, 270, 220));

        logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 100, 52), 2));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 110));
        getContentPane().add(prog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 270, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/robinpendergastphoto.jpg"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(440, 330));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginasActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        
           masuk();
            
        
        
    }//GEN-LAST:event_loginActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        keluar(cek);
       
       
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            masuk();
        }
        
    }//GEN-LAST:event_loginKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formKeyTyped
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public  ImageIcon scalegmbr(int width,int height){
       Image image=new ImageIcon(getClass().getResource("/gambar/the-bookstore-logo-design.png")).getImage();
       return new ImageIcon(image.getScaledInstance(width,height, SCALE_SMOOTH));
    }
    private void open_db(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/bookstore","root","");
        
    }   
    catch (ClassNotFoundException | SQLException e) {
    JOptionPane.showMessageDialog(this,"Database Error");
  System.exit(0);
    }
}
    private void escExit(){
      
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"),"exit");
        this.getRootPane().getActionMap().put("exit",new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                keluar(cek);
                
            }
        });
    }
    private void keluar(boolean m){
        if(m==true){
           String pil[]={"Ya","Tidak"};
           int exit=JOptionPane.showOptionDialog(null, "Apakah anda yakin ingin keluar program?","Keluar Program",YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE,null,pil,pil[0]);
           if(exit==JOptionPane.YES_OPTION){
                System.exit(0);
            } 
        }
        
    }
    private void log(){
        this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ENTER"),"masok");
        this.getRootPane().getActionMap().put("masok",new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                masuk();
            }
        });
    }
    private void masuk(){
      
       id.setEditable(false);
       loginas.setEnabled(false);
       password.setEditable(false);
       prog.setIndeterminate(true);
       login.setEnabled(false);
       cek=false;
        if(id.getText().equals("0")){
            
            try {
            pS=con.prepareStatement("select ID,Password from karyawanm where ID='0' and Password=md5(?)");
            pS.setString(1,String.valueOf(password.getPassword()));
            rS=pS.executeQuery();
            if(rS.next()){
                done=true;
              
               Worker work=new Worker(this,id.getText(),(String) loginas.getSelectedItem());
               work.execute();
              
            }
            else {
               
                JOptionPane.showMessageDialog(null,"Username/Password tidak valid");
            }
            }
            catch(SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } 
        }
        else  if(loginas.getSelectedItem()=="Kasir"){
                try {
                pS=con.prepareStatement("select ID,Password,TglKerja,TglBerhenti from karyawanm where ID COLLATE latin1_bin LIKE ? and Password=md5(?)");
                pS.setString(1,id.getText());
                pS.setString(2,String.valueOf(password.getPassword()));
                rS=pS.executeQuery();
                if(rS.next()){
                    Date dt=new Date();
                    if(rS.getDate("TglBerhenti")!=null){
                        
                        JOptionPane.showMessageDialog(null,"Anda sudah tidak terdaftar sebagai karyawan");
                    }
                    else if(rS.getDate("TglKerja")==null||rS.getDate("TglKerja").after(dt)){
                        SimpleDateFormat ft=new SimpleDateFormat("dd-MM-yyyy");
                        JOptionPane.showMessageDialog(null,"Anda  baru dapat mulai bekerja tanggal "+ft.format(rS.getDate("TglKerja")));
                    }
                    else{
                        done=true;
                        
                        Worker work=new Worker(this,id.getText(),(String) loginas.getSelectedItem());
                        work.execute();
                     }  
                }
                
                else {
                    
                    JOptionPane.showMessageDialog(null,"Username/Password tidak valid");
                }
                } 
                catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
            else if(loginas.getSelectedItem()=="Supervisor") {
                try {
                pS=con.prepareStatement("select supervisor.ID,karyawanm.Password,karyawanm.TglKerja,karyawanm.TglBerhenti from karyawanm inner join supervisor on karyawanm.ID=supervisor.ID where supervisor.ID COLLATE latin1_bin LIKE ? and karyawanm.Password=md5(?)");
                pS.setString(1,id.getText());
                pS.setString(2,String.valueOf(password.getPassword()));
                rS=pS.executeQuery();
                if(rS.next()){
                    Date dt=new Date();
                    if(rS.getDate("karyawanm.TglBerhenti")!=null){
                        
                        JOptionPane.showMessageDialog(null,"Anda sudah tidak terdaftar sebagai karyawan");
                    }
                    else if(rS.getDate("karyawanm.TglKerja")==null||rS.getDate("karyawanm.TglKerja").after(dt)){
                        SimpleDateFormat ft=new SimpleDateFormat("dd-MM-yyyy");
                        JOptionPane.showMessageDialog(null,"Anda  baru dapat mulai bekerja tanggal "+ft.format(rS.getDate("karyawanm.TglKerja")));
                    }
                    else{
                       
                            done=true;
                            
                            Worker work=new Worker(this,id.getText(),(String) loginas.getSelectedItem());
                            work.execute();
                            
                            
                        }
                        
                        
                    }
                
                else {
                    
                    JOptionPane.showMessageDialog(null,"Username/Password tidak valid");
                }
                }
                
                catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } 
            }
            else {
                JOptionPane.showMessageDialog(null,"Username/Password tidak valid");
            }
        if(done!=true){
            prog.setIndeterminate(false);
            id.setEditable(true);
            cek=true;
            loginas.setEnabled(true);
            password.setEditable(true);
            login.setEnabled(true);
        }
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JComboBox<String> loginas;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField password;
    private javax.swing.JProgressBar prog;
    // End of variables declaration//GEN-END:variables

}
