/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dinus.bookstore;

import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author ASUS
 */
public class PanelPic extends javax.swing.JFrame {

    /**
     * Creates new form PanelPic
     */
    ImageIcon yay;
   Statement stm;
   ResultSet rs;
   List<PanelPic> first;
   int value;
   boolean ada=true;
 Connection con;
    public PanelPic(Connection con,int value,List<PanelPic> first) {
        this.con=con;
        this.first=first;
        this.value=value;
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Gambar Buku ("+value+")");
        this.setIconImage(new ImageIcon(getClass().getResource("/gambar/the-bookstore-logo-design.png")).getImage());
         esc();
       try {
           stm=con.createStatement();
           rs=stm.executeQuery("select Gambar from bukum where Kode="+this.value);
           if(rs.next()){
                BufferedImage im;
                try {
                    im = ImageIO.read(rs.getBinaryStream("Gambar"));
                    yay=new ImageIcon(im);
               jLabel1.setIcon(scalegmbr(jLabel1.getWidth(), jLabel1.getHeight()));
                } catch (IOException ex) {
                    Logger.getLogger(PanelPic.class.getName()).log(Level.SEVERE, null, ex);
                } 
           }
           else {
               ada=false;
               jLabel1.setIcon(null);
           }
           
           
       } catch (SQLException ex) {
           Logger.getLogger(PanelPic.class.getName()).log(Level.SEVERE, null, ex);
       }
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Iterator<PanelPic> itr=first.listIterator();
        while(itr.hasNext()){
            PanelPic x=itr.next();
            if(x.value==this.value){
                itr.remove();
                break;
            }
        }
        this.dispose();
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
public ImageIcon scalegmbr(int width,int height){
      
       Image image=yay.getImage();
       
       return new ImageIcon(image.getScaledInstance(width,height, SCALE_SMOOTH));
    }
public void esc(){
    this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"),"exit");
        this.getRootPane().getActionMap().put("exit",new AbstractAction(){
            
            @Override
            public void actionPerformed(ActionEvent ae) {
             Iterator<PanelPic> itr=first.listIterator();
             
        while(itr.hasNext()){
            PanelPic x=itr.next();
            if(x.value==value){
                itr.remove();
                break;
            }
        }   
            dispose();
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
